"""Render the README / dissertation figures from the final measured results.

Why a separate script from ``src/evaluation/figures.py``
-------------------------------------------------------
``src.evaluation.figures`` plots whatever is currently in
``datasets/processed/exp_*_results.json`` — that is the *live* reporting layer
for a run you just executed.

This script is different: it pins the **final reported figures** from the
authoritative Google Colab run (see ``results/final_run_results.json``) so the
charts in the README can be regenerated byte-for-byte by anyone, without access
to a GPU, API keys, or the multi-hour run itself. The numbers live in one dict
at the top of the file, so there is exactly one place to check them against the
results JSON.

Usage
-----
    python -X utf8 scripts/make_report_figures.py
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # headless-safe
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent.parent
FIG_DIR = ROOT / "docs" / "figures"
RESULTS = ROOT / "results" / "final_run_results.json"
DPI = 200

# --- palette ---------------------------------------------------------------
RUST = "#C1440E"
GOLD = "#E9A33C"
SKY = "#5DADE2"
DEEP = "#1B6699"
TEAL = "#00A387"
INK = "#1A1A2E"


def _load() -> dict:
    return json.loads(RESULTS.read_text(encoding="utf-8"))


def _style(ax) -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.tick_params(colors=INK, labelsize=11)
    for spine in ("left", "bottom"):
        ax.spines[spine].set_color("#999999")


# ---------------------------------------------------------------------------
# Figure 1 — Python: F1 by strategy
# ---------------------------------------------------------------------------
def fig_python_f1(data: dict) -> Path:
    python = data["python_securityeval"]
    labels = [
        "A: SAST only",
        "B: Single LLM (best)",
        "C: Hybrid SAST+LLM",
        "D: Multi-LLM Consensus",
    ]
    values = [
        python["exp_a_sast"]["f1"],
        python["exp_b_best_single_llm"]["f1"],
        python["exp_c_hybrid_best"]["f1"],
        python["exp_d_consensus"]["f1"],
    ]
    colors = [RUST, GOLD, SKY, DEEP]

    fig, ax = plt.subplots(figsize=(10, 5.2))
    bars = ax.bar(labels, values, color=colors, edgecolor=INK, linewidth=1.1, width=0.62)
    ax.axhline(1.0, ls="--", lw=1.0, color="#999999", zorder=0)
    ax.set_ylim(0, 1.12)
    ax.set_ylabel("F1 Score", fontsize=13, color=INK)
    ax.set_title(
        "VERDICT: Vulnerability Detection F1 by Strategy\n"
        f"(SecurityEval benchmark, n={python['n_samples']})",
        fontsize=14, fontweight="bold", color=INK, pad=14,
    )
    for bar, value in zip(bars, values):
        ax.text(
            bar.get_x() + bar.get_width() / 2, value + 0.028, f"{value:.3f}",
            ha="center", va="bottom", fontsize=13, fontweight="bold", color=INK,
        )
    _style(ax)
    fig.tight_layout()
    out = FIG_DIR / "fig1_python_f1_by_strategy.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    return out


# ---------------------------------------------------------------------------
# Figure 2 — Experiment F: adversarial robustness by transform
# ---------------------------------------------------------------------------
def fig_adversarial(data: dict) -> Path:
    expf = data["python_securityeval"]["exp_f_adversarial"]
    transforms = expf["per_transform"]
    labels = [t["transform"].replace("_", "\n") for t in transforms]
    robustness = [t["robustness"] for t in transforms]
    degradation = [t["degradation"] for t in transforms]

    x = range(len(labels))
    width = 0.38
    fig, ax = plt.subplots(figsize=(10.5, 5.4))
    b1 = ax.bar([i - width / 2 for i in x], robustness, width,
                label="Robustness", color=TEAL, edgecolor=INK, linewidth=1.0)
    b2 = ax.bar([i + width / 2 for i in x], degradation, width,
                label="Degradation", color=RUST, edgecolor=INK, linewidth=1.0)
    ax.axhline(1.0, ls="--", lw=1.2, color=INK, label="Baseline", zorder=0)

    ax.set_xticks(list(x))
    ax.set_xticklabels(labels, fontsize=10)
    ax.set_ylabel("Score", fontsize=12, color=INK)
    ax.set_ylim(min(0, min(degradation) - 0.06), 1.24)
    ax.set_title(
        "Exp F: Adversarial Robustness by Transform\n"
        f"(Overall robustness={expf['overall_robustness']}, "
        f"n={expf['n_cases']} cases)",
        fontsize=14, fontweight="bold", color=INK, pad=14,
    )
    for bars in (b1, b2):
        for bar in bars:
            height = bar.get_height()
            # Negative labels are placed just *above* the zero line, otherwise
            # they collide with the x-axis tick labels underneath.
            y_pos = height + 0.02 if height >= 0 else 0.02
            ax.text(
                bar.get_x() + bar.get_width() / 2, y_pos, f"{height:.3f}",
                ha="center", va="bottom", fontsize=10, color=INK,
            )
    ax.legend(frameon=True, fontsize=11, loc="upper right")
    _style(ax)
    fig.tight_layout()
    out = FIG_DIR / "fig2_adversarial_robustness.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    return out


# ---------------------------------------------------------------------------
# Figure 3 — PLC: the bias-corrected reversal
# ---------------------------------------------------------------------------
def fig_plc_differential(data: dict) -> Path:
    plc = data["plc_stmutants"]
    rows = plc["systems"]
    labels = [r["system"] for r in rows]
    kill = [r["kill_rate"] for r in rows]
    false_alarm = [r["false_alarm_rate"] for r in rows]
    corrected = [r["bias_corrected"] for r in rows]

    y = range(len(labels))
    height = 0.26
    fig, ax = plt.subplots(figsize=(10.5, 5.6))
    ax.barh([i + height for i in y], kill, height, label="Kill rate",
            color=SKY, edgecolor=INK, linewidth=0.9)
    ax.barh(list(y), false_alarm, height, label="False-alarm rate",
            color=RUST, edgecolor=INK, linewidth=0.9)
    ax.barh([i - height for i in y], corrected, height,
            label="Bias-corrected (kill − false alarm)",
            color=TEAL, edgecolor=INK, linewidth=0.9)

    ax.axvline(0, lw=1.0, color=INK)
    ax.set_yticks(list(y))
    ax.set_yticklabels(labels, fontsize=11)
    ax.invert_yaxis()
    ax.set_xlabel("Rate", fontsize=12, color=INK)
    ax.set_xlim(min(-0.1, min(corrected) - 0.08), 1.08)
    ax.set_title(
        "Exp ST: PLC Differential Discrimination (STMutants)\n"
        f"({plc['n_mutation_pairs']} mutation pairs + "
        f"{plc['n_identity_controls']} identity controls) — "
        "identity controls expose response bias",
        fontsize=13, fontweight="bold", color=INK, pad=14,
    )
    for i, value in enumerate(corrected):
        # Always label to the right of zero so a negative score cannot collide
        # with the y-axis tick labels on the left.
        ax.text(
            max(value, 0.0) + 0.015, i - height,
            f"{value:.3f}", va="center", ha="left",
            fontsize=10, fontweight="bold", color=INK,
        )
    ax.legend(frameon=True, fontsize=10, loc="lower right")
    _style(ax)
    fig.tight_layout()
    out = FIG_DIR / "fig3_plc_differential.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    return out


def generate_all() -> None:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    data = _load()
    for builder in (fig_python_f1, fig_adversarial, fig_plc_differential):
        path = builder(data)
        print(f"  wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    generate_all()
